### ISSUE TITLE
Bad translations detection

### ISSUE THREAD

**Issue by NicolasGuilloux** [mdevlamynck/elm-symfony-bridge#13]
There is a bug about the translations detection and conversion into an Elm module.

- `front.messages.fr.yaml` is not detected, therefore doesn't produce an El module.
- `front-messages.fr.yaml` creates a `Front-messages.elm` file but the module cannot be imported as the module shouldn't have a `-` character

**Comment by mdevlamynck** [comment]
* The `front.messages.fr.yaml` case is not handled by the `bazinga:js-translation:dump` we're relying on. I'm not sure we can do anything in that case.
* The `bazinga:js-translation:dump
