### ISSUE TITLE
The plugin assumes the webpack config file is defined at the root of the symfony project

### ISSUE THREAD

**Issue by aszenz** [mdevlamynck/elm-symfony-bridge#28]
The plugin js code executes `./bin/console` commands, assuming that the webpack process is started from the root of the project.
We have defined the webpack file inside assets, so this fails.
Is there a way to set the base directory

**Comment by mdevlamynck** [comment]
Shouldn't be too hard to add a config for the console / base directory path. I'll try to do it when I have some time but I'm welcoming a PR if you want to :)

**Comment by mdevlamynck** [comment]
I've pushed the `project-root` branch, can you try it and tell me if it works for you? I'm not sure if other path (outputFolder, elmRoot) need to use the new projectRoot as a prefix or not. Feedback is welcomed :) You'll find build instruction in the README.md.

**Comment by aszenz** [comment]
Thanks, I switched to the branch and installed the package via tar, got this error though on building my project:

```
webpack-cli] Failed to load '/home/xax/Desktop/xyz/assets/webpack.config.js' config
[webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'projectRoot'. These properties are valid:
   object { dev, outputFolder?, elmRoot?, elmVersion?, enableRouting?, lang?, enableTranslations?, urlPrefix?, envVariables? }
```

After adding the `projectRoot` to `webpack/schema.json` and rebuilding the package it worked, but i also get warnings like these

```
Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
Invalid dependencies may lead to broken watching and caching.
As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
Globs: They are not supported. Pass absolute path to the directory as context dependencies.
The following invalid values have been reported:
 * "app"
 * "config"
 * "src"
```

**Comment by mdevlamynck** [comment]
Oh right sorry, forgot to update the schema.json. Should be better now.

**Comment by aszenz** [comment]
Any idea about the warnings, is it something related to the plugin

**Comment by mdevlamynck** [comment]
What version of webpack are you using? It looks like it's complaining about some path the plugin is listing as containing dependencies (to trigger rebuild when a file changes). It makes sense that the path would be wrong but the part about requiring absolute paths means I'll have to update that code anyway.

**Comment by aszenz** [comment]
Here's our directory setup

```
/composer.json
/bin/console
/assets/package.json
/assets/elm.json
/assets/webpack.config.js
/assets/FirstElmApp/src -- this goes into elm's source directories
/assets/FirstElmApp/tests -- this also goes into elm's source directories
/assets/SecondElmApp/src 
...
/public
```

So yes elm root should be relative to webpack config file while the output folder is indeed relative to project path.

`

**Comment by mdevlamynck** [comment]
Right, ok. I've update the branch accordingly. I'm having a weird crash though, so it's not done and I don't have the time to debug it right now. I'll try to fix it in the next few days.

**Comment by mdevlamynck** [comment]
Should work now :)

**Comment by aszenz** [comment]
Thanks, seems to work well, any idea why the translation folder in public directory is also generated, what is the use of `outputFolder`, i would think having `elmRoot` is enough to generate files

**Comment by mdevlamynck** [comment]
`outputFolder` is where generated files are stored (defaults to public, close to the defaults of [BazingaJsTranslationBundle](https://github.com/willdurand/BazingaJsTranslationBundle)). It's used to dump translations so that the plugin can read them.

**Comment by aszenz** [comment]
I see so these js translation files are intermediate files for generating actual elm files. Once the elm files are generated we don't need the js files right?

**Comment by mdevlamynck** [comment]
Yes we could drop them. The original idea of bazinga is that it's public so that the front can load them. I could change the default to `elm-stuff/generated-code/elm-symfony-bridge`, that's what the parcel version of this plugin does.

**Comment by aszenz** [comment]
Yes elm-stuff is in assets which is also the root of the elm (where elm.json lives)
Yes i do think generating the js files should be temporary, not sure where to place it, I don't think the public folder is the destination for it

**Comment by mdevlamynck** [comment]
I've changed the default for outputFolder in the branch. Can you confirm that it works before I make a release?

**Comment by aszenz** [comment]
Seems to be working fine. Thanks
