### ISSUE TITLE
Handle errors from debug routes command gracefully

### ISSUE THREAD

**Issue by aszenz** [mdevlamynck/elm-symfony-bridge#31]
`Error: Command failed: /home/asrar/Desktop/qbil-trade/bin/console debug:router --format=json --env=dev`

I keep webpack dev server running while developing, sometimes the file is saved with syntax errors, and then the dev server gets stuck because of the exception from the debug routes command.

I have to restart the dev-server for it to continue working again, even though the syntax error is no longer present.

Is their a way for the dev server to continue running in this case

**Comment by mdevlamynck** [comment]
Fixed in version v1.3.1 :)
