### ISSUE TITLE
Add vite support

### ISSUE THREAD

**Issue by aszenz** [mdevlamynck/elm-symfony-bridge#32]
[Vite](https://vitejs.dev/) (https://github.com/hmsk/vite-plugin-elm) is gaining foothold in both elm and symfony ecosystems(https://symfony-vite.pentatrion.com/), it's fast and provides good defaults out of the box.

**Comment by mdevlamynck** [comment]
I just pushed the [vite](https://github.com/mdevlamynck/elm-symfony-bridge/tree/vite/vite) branch. Can you try it and tell me if it works for you before I make a release? I never used vite before I might have overlooked something or missed a bug.

**Comment by aszenz** [comment]
> I just pushed the [vite](https://github.com/mdevlamynck/elm-symfony-bridge/tree/vite/vite) branch. Can you try it and tell me if it works for you before I make a release? I never used vite before I might have overlooked something or missed a bug.

I just checked it for our symfony project by doing these steps:
```
git clone https://github.com/mdevlamynck/elm-symfony-bridge
git checkout vite
cd vite
yarn install
yarn run build
yarn pack
```
Then installing in our project and configuring it
```js
elmSymfonyPlugin({
    projectRoot: '../',
    elmRoot: './Common/__generated',
    outputFolder: '/tmp',
    elmVersion: '0.19',
    enableRouting: true,
    urlPrefix: '/build',
    enableTranslations: false,
}),
```

Running both dev and production builds work great, `Routing.elm` and `Trans` module are generated in the right places.

**Comment by mdevlamynck** [comment]
Looks good I'll make a release.

**Comment by mdevlamynck** [comment]
Published https://www.npmjs.com/package/vite-plugin-elm-symfony-bridge.
